package meshtastic

// radioConfigSchemaProperties returns the JSON schema properties for radio
// configuration fields. Used in both the default and per-device schemas.
func radioConfigSchemaProperties() map[string]interface{} {
	return map[string]interface{}{
		"radio_region": map[string]interface{}{
			"type":        "string",
			"title":       "Region",
			"description": "LoRa regulatory region",
			"oneOf": []interface{}{
				map[string]interface{}{"const": "US", "title": "United States"},
				map[string]interface{}{"const": "EU_433", "title": "Europe 433 MHz"},
				map[string]interface{}{"const": "EU_868", "title": "Europe 868 MHz"},
				map[string]interface{}{"const": "CN", "title": "China"},
				map[string]interface{}{"const": "JP", "title": "Japan"},
				map[string]interface{}{"const": "ANZ", "title": "Australia / NZ"},
				map[string]interface{}{"const": "KR", "title": "South Korea"},
				map[string]interface{}{"const": "TW", "title": "Taiwan"},
				map[string]interface{}{"const": "RU", "title": "Russia"},
				map[string]interface{}{"const": "IN", "title": "India"},
				map[string]interface{}{"const": "NZ_865", "title": "New Zealand 865 MHz"},
				map[string]interface{}{"const": "TH", "title": "Thailand"},
				map[string]interface{}{"const": "LORA_24", "title": "LoRa 2.4 GHz"},
				map[string]interface{}{"const": "UA_433", "title": "Ukraine 433 MHz"},
				map[string]interface{}{"const": "UA_868", "title": "Ukraine 868 MHz"},
				map[string]interface{}{"const": "MY_433", "title": "Malaysia 433 MHz"},
				map[string]interface{}{"const": "MY_919", "title": "Malaysia 919 MHz"},
				map[string]interface{}{"const": "SG_923", "title": "Singapore 923 MHz"},
				map[string]interface{}{"const": "PH_433", "title": "Philippines 433 MHz"},
				map[string]interface{}{"const": "PH_868", "title": "Philippines 868 MHz"},
				map[string]interface{}{"const": "PH_915", "title": "Philippines 915 MHz"},
			},
			"ui:group": "radio",
			"ui:order": 0,
		},
		"radio_preset": map[string]interface{}{
			"type":        "string",
			"title":       "Modem Preset",
			"description": "LoRa modem preset (range/speed tradeoff)",
			"oneOf": []interface{}{
				map[string]interface{}{"const": "long_fast", "title": "Long Range / Fast"},
				map[string]interface{}{"const": "long_moderate", "title": "Long Range / Moderate"},
				map[string]interface{}{"const": "long_turbo", "title": "Long Range / Turbo"},
				map[string]interface{}{"const": "medium_slow", "title": "Medium Range / Slow"},
				map[string]interface{}{"const": "medium_fast", "title": "Medium Range / Fast"},
				map[string]interface{}{"const": "short_slow", "title": "Short Range / Slow"},
				map[string]interface{}{"const": "short_fast", "title": "Short Range / Fast"},
				map[string]interface{}{"const": "short_turbo", "title": "Short Range / Turbo"},
			},
			"ui:group": "radio",
			"ui:order": 1,
		},
		"radio_tx_power": map[string]interface{}{
			"type":        "integer",
			"title":       "TX Power",
			"description": "Transmit power (0 = max legal default)",
			"default":     0,
			"ui:unit":     "dBm",
			"ui:group":    "radio",
			"ui:order":    2,
		},
		"radio_tx_enabled": map[string]interface{}{
			"type":        "boolean",
			"title":       "TX Enabled",
			"description": "Enable LoRa transmission",
			"ui:group":    "radio",
			"ui:order":    3,
		},
		"device_role": map[string]interface{}{
			"type":        "string",
			"title":       "Device Role",
			"description": "Device mesh role",
			"oneOf": []interface{}{
				map[string]interface{}{"const": "client", "title": "Client"},
				map[string]interface{}{"const": "client_mute", "title": "Client (Mute)"},
				map[string]interface{}{"const": "router", "title": "Router"},
				map[string]interface{}{"const": "tracker", "title": "Tracker"},
				map[string]interface{}{"const": "sensor", "title": "Sensor"},
				map[string]interface{}{"const": "tak", "title": "TAK"},
				map[string]interface{}{"const": "client_hidden", "title": "Client (Hidden)"},
				map[string]interface{}{"const": "tak_tracker", "title": "TAK Tracker"},
				map[string]interface{}{"const": "router_late", "title": "Router (Late)"},
			},
			"ui:group": "device",
			"ui:order": 0,
		},
		"device_rebroadcast": map[string]interface{}{
			"type":        "string",
			"title":       "Rebroadcast Mode",
			"description": "Rebroadcast mode for received packets",
			"oneOf": []interface{}{
				map[string]interface{}{"const": "all", "title": "All"},
				map[string]interface{}{"const": "local_only", "title": "Local Only"},
				map[string]interface{}{"const": "known_only", "title": "Known Only"},
				map[string]interface{}{"const": "none", "title": "None"},
			},
			"ui:group": "device",
			"ui:order": 1,
		},
		"position_interval_secs": map[string]interface{}{
			"type":        "integer",
			"title":       "Position Interval",
			"description": "Position broadcast interval (0 = default 15min)",
			"default":     0,
			"minimum":     0,
			"ui:unit":     "s",
			"ui:group":    "position",
			"ui:order":    0,
		},
		"position_smart": map[string]interface{}{
			"type":        "boolean",
			"title":       "Smart Position",
			"description": "Enable smart position broadcasting (distance-based)",
			"ui:group":    "position",
			"ui:order":    1,
		},
		"position_gps_mode": map[string]interface{}{
			"type":        "string",
			"title":       "GPS Mode",
			"description": "GPS mode",
			"oneOf": []interface{}{
				map[string]interface{}{"const": "enabled", "title": "Enabled"},
				map[string]interface{}{"const": "disabled", "title": "Disabled"},
				map[string]interface{}{"const": "not_present", "title": "Not Present"},
			},
			"ui:group": "position",
			"ui:order": 2,
		},
		"owner_long_name": map[string]interface{}{
			"type":           "string",
			"title":          "Long Name",
			"description":    "Device owner long name (displayed on mesh)",
			"ui:placeholder": "e.g. My Radio",
			"ui:group":       "identity",
			"ui:order":       0,
		},
		"owner_short_name": map[string]interface{}{
			"type":           "string",
			"title":          "Short Name",
			"description":    "Device owner short name (2-4 chars for OLED)",
			"ui:placeholder": "e.g. MR",
			"ui:group":       "identity",
			"ui:order":       1,
		},
		"channel_psk": map[string]interface{}{
			"type":           "string",
			"title":          "Channel PSK",
			"description":    "Primary channel pre-shared key (base64, 16 or 32 bytes for AES128/256)",
			"ui:widget":      "password",
			"ui:placeholder": "base64 encoded key",
			"ui:group":       "channel",
			"ui:order":       0,
		},
		"channel_name": map[string]interface{}{
			"type":           "string",
			"title":          "Channel Name",
			"description":    "Primary channel name",
			"ui:placeholder": "e.g. LongFast",
			"ui:group":       "channel",
			"ui:order":       1,
		},
	}
}
