// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file proto/world.proto (package world, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EntityChangeEvent, EntityChangeRequest, EntityChangeResponse, GetEntityRequest, GetEntityResponse, ListEntitiesRequest, ListEntitiesResponse, ObserverRequest, ObserverState } from "./world_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * interact with the world model
 *
 * @generated from service world.WorldService
 */
export const WorldService = {
  typeName: "world.WorldService",
  methods: {
    /**
     * list entities present in the world once
     *
     * @generated from rpc world.WorldService.ListEntities
     */
    listEntities: {
      name: "ListEntities",
      I: ListEntitiesRequest,
      O: ListEntitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * request every detail about one entity
     *
     * @generated from rpc world.WorldService.GetEntity
     */
    getEntity: {
      name: "GetEntity",
      I: GetEntityRequest,
      O: GetEntityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * continously monitor entities present in the world. this is used by downstream C2.
     *
     * @generated from rpc world.WorldService.WatchEntities
     */
    watchEntities: {
      name: "WatchEntities",
      I: ListEntitiesRequest,
      O: EntityChangeEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * create or update an entity. used by capabilities
     *
     * @generated from rpc world.WorldService.Push
     */
    push: {
      name: "Push",
      I: EntityChangeRequest,
      O: EntityChangeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * observe all observers so controllers can pause georegions nobody is looking at
     *
     * @generated from rpc world.WorldService.Observe
     */
    observe: {
      name: "Observe",
      I: ObserverRequest,
      O: ObserverState,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

