/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "sans-medium": ["Inter-Medium", "sans-serif"],
        "sans-semibold": ["Inter-SemiBold", "sans-serif"],
        "sans-bold": ["Inter-Bold", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        8: "8px",
        9: "9px",
        10: "10px",
        11: "11px",
        12: "12px",
        13: "13px",
        15: "15px",
        18: "18px",
      },
      opacity: {
        2: "0.02",
        3: "0.03",
        4: "0.04",
        6: "0.06",
        7: "0.07",
        8: "0.08",
        12: "0.12",
        85: "0.85",
        88: "0.88",
        92: "0.92",
      },
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        foreground: "rgb(var(--color-foreground) / <alpha-value>)",
        card: "rgb(var(--color-card) / <alpha-value>)",
        "card-foreground": "rgb(var(--color-card-foreground) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        "muted-foreground": "rgb(var(--color-muted-foreground) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        input: "rgb(var(--color-input) / <alpha-value>)",
        ring: "rgb(var(--color-ring) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-foreground": "rgb(var(--color-primary-foreground) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-foreground": "rgb(var(--color-secondary-foreground) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-foreground": "rgb(var(--color-accent-foreground) / <alpha-value>)",
        destructive: "rgb(var(--color-destructive) / <alpha-value>)",
        "destructive-foreground": "rgb(var(--color-destructive-foreground) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-foreground": "rgb(var(--color-success-foreground) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        pending: "rgb(var(--color-pending) / <alpha-value>)",
        "pending-foreground": "rgb(var(--color-pending-foreground) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        red: "rgb(var(--color-red) / <alpha-value>)",
        "red-foreground": "rgb(var(--color-red-foreground) / <alpha-value>)",
        green: "rgb(var(--color-green) / <alpha-value>)",
        blue: "rgb(var(--color-blue) / <alpha-value>)",
        "blue-foreground": "rgb(var(--color-blue-foreground) / <alpha-value>)",
        yellow: "rgb(var(--color-yellow) / <alpha-value>)",
        violet: "rgb(var(--color-violet) / <alpha-value>)",
        "milsymbol-friend": "rgb(128 224 255 / <alpha-value>)",
        "milsymbol-hostile": "rgb(255 128 128 / <alpha-value>)",
        "milsymbol-neutral": "rgb(170 255 170 / <alpha-value>)",
        "milsymbol-unknown": "rgb(255 255 128 / <alpha-value>)",
        "on-surface": "rgb(var(--color-foreground) / <alpha-value>)",
        "surface-overlay": "rgb(var(--color-glass) / <alpha-value>)",
        glass: {
          DEFAULT: "rgb(var(--color-glass) / 0.05)",
          hover: "rgb(var(--color-glass) / 0.08)",
          active: "rgb(var(--color-glass) / 0.10)",
          strong: "rgb(var(--color-glass) / 0.15)",
        },
        control: {
          DEFAULT: "rgb(var(--color-control) / <alpha-value>)",
          hover: "rgb(var(--color-control-hover) / <alpha-value>)",
          fg: "rgb(var(--color-control-fg) / <alpha-value>)",
          "fg-active": "rgb(var(--color-control-fg-active) / <alpha-value>)",
          "fg-disabled": "rgb(var(--color-control-fg-disabled) / <alpha-value>)",
          border: "rgb(var(--color-control-border) / <alpha-value>)",
          "border-hover": "rgb(var(--color-control-border-hover) / <alpha-value>)",
          input: "rgb(var(--color-control-input) / <alpha-value>)",
          "text-muted": "rgb(var(--color-control-text-muted) / <alpha-value>)",
        },
        "active-green": "rgb(var(--color-active-green) / <alpha-value>)",
      },
      zIndex: {
        1: "1",
        2: "2",
        5: "5",
        9: "9",
      },
      borderWidth: {
        hairline: 1,
      },
    },
  },
  plugins: [
    ({ addBase }) =>
      addBase({
        ":root": {
          "--color-background": "220 220 222",
          "--color-foreground": "24 24 26",
          "--color-card": "228 228 230",
          "--color-card-foreground": "24 24 26",
          "--color-muted": "202 202 206",
          "--color-muted-foreground": "72 72 76",
          "--color-border": "188 188 192",
          "--color-input": "214 214 218",
          "--color-ring": "148 148 152",
          "--color-primary": "202 202 206",
          "--color-primary-foreground": "38 38 42",
          "--color-secondary": "214 214 218",
          "--color-secondary-foreground": "38 38 42",
          "--color-accent": "206 206 210",
          "--color-accent-foreground": "38 38 42",
          "--color-destructive": "190 18 18",
          "--color-destructive-foreground": "38 38 45",
          "--color-success": "46 125 100",
          "--color-success-foreground": "2 90 65",
          "--color-warning": "168 52 8",
          "--color-pending": "168 88 0",
          "--color-pending-foreground": "132 58 0",
          "--color-info": "55 70 90",
          "--color-red": "190 18 18",
          "--color-red-foreground": "148 18 18",
          "--color-green": "14 108 48",
          "--color-blue": "28 82 208",
          "--color-blue-foreground": "20 65 178",
          "--color-yellow": "138 82 0",
          "--color-violet": "108 36 112",
          "--color-glass": "0 0 0",
          "--color-control": "226 226 228",
          "--color-control-hover": "216 216 218",
          "--color-control-fg": "72 72 78",
          "--color-control-fg-active": "24 24 26",
          "--color-control-fg-disabled": "164 164 170",
          "--color-control-border": "180 180 184",
          "--color-control-border-hover": "148 148 152",
          "--color-control-input": "240 240 242",
          "--color-control-text-muted": "84 84 90",
          "--color-active-green": "40 180 99",
        },
        ".dark:root": {
          "--color-background": "22 22 22",
          "--color-foreground": "220 220 220",
          "--color-card": "27 27 27",
          "--color-card-foreground": "220 220 220",
          "--color-muted": "33 33 33",
          "--color-muted-foreground": "153 153 153",
          "--color-border": "60 60 60",
          "--color-input": "27 27 27",
          "--color-ring": "65 65 65",
          "--color-primary": "65 65 65",
          "--color-primary-foreground": "188 188 188",
          "--color-secondary": "60 60 60",
          "--color-secondary-foreground": "188 188 188",
          "--color-accent": "65 65 65",
          "--color-accent-foreground": "188 188 188",
          "--color-destructive": "205 24 24",
          "--color-destructive-foreground": "188 188 188",
          "--color-success": "61 141 122",
          "--color-success-foreground": "52 211 153",
          "--color-warning": "249 87 56",
          "--color-pending": "245 158 11",
          "--color-pending-foreground": "251 191 36",
          "--color-info": "130 148 165",
          "--color-red": "205 24 24",
          "--color-red-foreground": "248 113 113",
          "--color-green": "34 197 94",
          "--color-blue": "59 130 246",
          "--color-blue-foreground": "125 185 255",
          "--color-yellow": "247 239 129",
          "--color-violet": "126 46 132",
          "--color-glass": "255 255 255",
          "--color-control": "34 34 34",
          "--color-control-hover": "42 42 46",
          "--color-control-fg": "163 163 163",
          "--color-control-fg-active": "220 220 220",
          "--color-control-fg-disabled": "113 113 113",
          "--color-control-border": "39 39 42",
          "--color-control-border-hover": "63 63 70",
          "--color-control-input": "9 9 11",
          "--color-control-text-muted": "140 140 140",
          "--color-active-green": "34 197 94",
        },
      }),
  ],
};
