// reverse engineered meshtastic serial wire protocol from a t-echo
// this seems to work just fine, but only tested what we need
//go:generate protoc --go_out=. --go_opt=paths=source_relative mesh.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.1
// source: mesh.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Port int32

const (
	Port_PORT_UNKNOWN       Port = 0
	Port_PORT_TEXT          Port = 1
	Port_PORT_POSITION      Port = 3
	Port_PORT_NODEINFO      Port = 4
	Port_PORT_TELEMETRY     Port = 67
	Port_PORT_TAK           Port = 72
	Port_PORT_TAK_FORWARDER Port = 257
	Port_PORT_HYDRIS        Port = 78
)

// Enum value maps for Port.
var (
	Port_name = map[int32]string{
		0:   "PORT_UNKNOWN",
		1:   "PORT_TEXT",
		3:   "PORT_POSITION",
		4:   "PORT_NODEINFO",
		67:  "PORT_TELEMETRY",
		72:  "PORT_TAK",
		257: "PORT_TAK_FORWARDER",
		78:  "PORT_HYDRIS",
	}
	Port_value = map[string]int32{
		"PORT_UNKNOWN":       0,
		"PORT_TEXT":          1,
		"PORT_POSITION":      3,
		"PORT_NODEINFO":      4,
		"PORT_TELEMETRY":     67,
		"PORT_TAK":           72,
		"PORT_TAK_FORWARDER": 257,
		"PORT_HYDRIS":        78,
	}
)

func (x Port) Enum() *Port {
	p := new(Port)
	*p = x
	return p
}

func (x Port) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Port) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (Port) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x Port) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Port.Descriptor instead.
func (Port) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port Port   `protobuf:"varint,1,opt,name=port,proto3,enum=meshpb.Port" json:"port,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetPort() Port {
	if x != nil {
		return x.Port
	}
	return Port_PORT_UNKNOWN
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src uint32 `protobuf:"fixed32,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst uint32 `protobuf:"fixed32,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Ch  uint32 `protobuf:"varint,3,opt,name=ch,proto3" json:"ch,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Packet_Decoded
	//	*Packet_Encrypted
	Body     isPacket_Body `protobuf_oneof:"body"`
	Id       uint32        `protobuf:"fixed32,6,opt,name=id,proto3" json:"id,omitempty"`
	RxTime   uint32        `protobuf:"fixed32,7,opt,name=rx_time,json=rxTime,proto3" json:"rx_time,omitempty"`
	RxSnr    float32       `protobuf:"fixed32,8,opt,name=rx_snr,json=rxSnr,proto3" json:"rx_snr,omitempty"`
	HopLimit uint32        `protobuf:"varint,9,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	WantAck  bool          `protobuf:"varint,10,opt,name=want_ack,json=wantAck,proto3" json:"want_ack,omitempty"`
	RxRssi   int32         `protobuf:"varint,12,opt,name=rx_rssi,json=rxRssi,proto3" json:"rx_rssi,omitempty"`
	HopStart uint32        `protobuf:"varint,15,opt,name=hop_start,json=hopStart,proto3" json:"hop_start,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *Packet) GetSrc() uint32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Packet) GetDst() uint32 {
	if x != nil {
		return x.Dst
	}
	return 0
}

func (x *Packet) GetCh() uint32 {
	if x != nil {
		return x.Ch
	}
	return 0
}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Packet) GetDecoded() *Payload {
	if x, ok := x.GetBody().(*Packet_Decoded); ok {
		return x.Decoded
	}
	return nil
}

func (x *Packet) GetEncrypted() []byte {
	if x, ok := x.GetBody().(*Packet_Encrypted); ok {
		return x.Encrypted
	}
	return nil
}

func (x *Packet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Packet) GetRxTime() uint32 {
	if x != nil {
		return x.RxTime
	}
	return 0
}

func (x *Packet) GetRxSnr() float32 {
	if x != nil {
		return x.RxSnr
	}
	return 0
}

func (x *Packet) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *Packet) GetWantAck() bool {
	if x != nil {
		return x.WantAck
	}
	return false
}

func (x *Packet) GetRxRssi() int32 {
	if x != nil {
		return x.RxRssi
	}
	return 0
}

func (x *Packet) GetHopStart() uint32 {
	if x != nil {
		return x.HopStart
	}
	return 0
}

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_Decoded struct {
	Decoded *Payload `protobuf:"bytes,4,opt,name=decoded,proto3,oneof"`
}

type Packet_Encrypted struct {
	Encrypted []byte `protobuf:"bytes,5,opt,name=encrypted,proto3,oneof"`
}

func (*Packet_Decoded) isPacket_Body() {}

func (*Packet_Encrypted) isPacket_Body() {}

type ToRadio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ToRadio_Packet
	//	*ToRadio_WantConfigId
	Msg isToRadio_Msg `protobuf_oneof:"msg"`
}

func (x *ToRadio) Reset() {
	*x = ToRadio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToRadio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToRadio) ProtoMessage() {}

func (x *ToRadio) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToRadio.ProtoReflect.Descriptor instead.
func (*ToRadio) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (m *ToRadio) GetMsg() isToRadio_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ToRadio) GetPacket() *Packet {
	if x, ok := x.GetMsg().(*ToRadio_Packet); ok {
		return x.Packet
	}
	return nil
}

func (x *ToRadio) GetWantConfigId() uint32 {
	if x, ok := x.GetMsg().(*ToRadio_WantConfigId); ok {
		return x.WantConfigId
	}
	return 0
}

type isToRadio_Msg interface {
	isToRadio_Msg()
}

type ToRadio_Packet struct {
	Packet *Packet `protobuf:"bytes,1,opt,name=packet,proto3,oneof"`
}

type ToRadio_WantConfigId struct {
	WantConfigId uint32 `protobuf:"varint,3,opt,name=want_config_id,json=wantConfigId,proto3,oneof"`
}

func (*ToRadio_Packet) isToRadio_Msg() {}

func (*ToRadio_WantConfigId) isToRadio_Msg() {}

type FromRadio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*FromRadio_Packet
	//	*FromRadio_Self
	//	*FromRadio_Node
	//	*FromRadio_Config
	//	*FromRadio_Log
	//	*FromRadio_ConfigCompleteId
	//	*FromRadio_ModConfig
	//	*FromRadio_Channel
	//	*FromRadio_Queue
	Msg isFromRadio_Msg `protobuf_oneof:"msg"`
}

func (x *FromRadio) Reset() {
	*x = FromRadio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromRadio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromRadio) ProtoMessage() {}

func (x *FromRadio) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromRadio.ProtoReflect.Descriptor instead.
func (*FromRadio) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *FromRadio) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *FromRadio) GetMsg() isFromRadio_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *FromRadio) GetPacket() *Packet {
	if x, ok := x.GetMsg().(*FromRadio_Packet); ok {
		return x.Packet
	}
	return nil
}

func (x *FromRadio) GetSelf() *NodeSelf {
	if x, ok := x.GetMsg().(*FromRadio_Self); ok {
		return x.Self
	}
	return nil
}

func (x *FromRadio) GetNode() *NodeEntry {
	if x, ok := x.GetMsg().(*FromRadio_Node); ok {
		return x.Node
	}
	return nil
}

func (x *FromRadio) GetConfig() *RadioConfig {
	if x, ok := x.GetMsg().(*FromRadio_Config); ok {
		return x.Config
	}
	return nil
}

func (x *FromRadio) GetLog() *Log {
	if x, ok := x.GetMsg().(*FromRadio_Log); ok {
		return x.Log
	}
	return nil
}

func (x *FromRadio) GetConfigCompleteId() uint32 {
	if x, ok := x.GetMsg().(*FromRadio_ConfigCompleteId); ok {
		return x.ConfigCompleteId
	}
	return 0
}

func (x *FromRadio) GetModConfig() *ModConfig {
	if x, ok := x.GetMsg().(*FromRadio_ModConfig); ok {
		return x.ModConfig
	}
	return nil
}

func (x *FromRadio) GetChannel() *Chan {
	if x, ok := x.GetMsg().(*FromRadio_Channel); ok {
		return x.Channel
	}
	return nil
}

func (x *FromRadio) GetQueue() *TxQueue {
	if x, ok := x.GetMsg().(*FromRadio_Queue); ok {
		return x.Queue
	}
	return nil
}

type isFromRadio_Msg interface {
	isFromRadio_Msg()
}

type FromRadio_Packet struct {
	Packet *Packet `protobuf:"bytes,2,opt,name=packet,proto3,oneof"`
}

type FromRadio_Self struct {
	Self *NodeSelf `protobuf:"bytes,3,opt,name=self,proto3,oneof"`
}

type FromRadio_Node struct {
	Node *NodeEntry `protobuf:"bytes,4,opt,name=node,proto3,oneof"`
}

type FromRadio_Config struct {
	Config *RadioConfig `protobuf:"bytes,5,opt,name=config,proto3,oneof"`
}

type FromRadio_Log struct {
	Log *Log `protobuf:"bytes,6,opt,name=log,proto3,oneof"`
}

type FromRadio_ConfigCompleteId struct {
	ConfigCompleteId uint32 `protobuf:"varint,7,opt,name=config_complete_id,json=configCompleteId,proto3,oneof"`
}

type FromRadio_ModConfig struct {
	ModConfig *ModConfig `protobuf:"bytes,9,opt,name=mod_config,json=modConfig,proto3,oneof"`
}

type FromRadio_Channel struct {
	Channel *Chan `protobuf:"bytes,10,opt,name=channel,proto3,oneof"`
}

type FromRadio_Queue struct {
	Queue *TxQueue `protobuf:"bytes,11,opt,name=queue,proto3,oneof"`
}

func (*FromRadio_Packet) isFromRadio_Msg() {}

func (*FromRadio_Self) isFromRadio_Msg() {}

func (*FromRadio_Node) isFromRadio_Msg() {}

func (*FromRadio_Config) isFromRadio_Msg() {}

func (*FromRadio_Log) isFromRadio_Msg() {}

func (*FromRadio_ConfigCompleteId) isFromRadio_Msg() {}

func (*FromRadio_ModConfig) isFromRadio_Msg() {}

func (*FromRadio_Channel) isFromRadio_Msg() {}

func (*FromRadio_Queue) isFromRadio_Msg() {}

type NodeSelf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeNum uint32 `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
}

func (x *NodeSelf) Reset() {
	*x = NodeSelf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSelf) ProtoMessage() {}

func (x *NodeSelf) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSelf.ProtoReflect.Descriptor instead.
func (*NodeSelf) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *NodeSelf) GetNodeNum() uint32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LongName  string `protobuf:"bytes,2,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	ShortName string `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Mac       []byte `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	Hw        uint32 `protobuf:"varint,5,opt,name=hw,proto3" json:"hw,omitempty"`
	Role      uint32 `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *Peer) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Peer) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *Peer) GetHw() uint32 {
	if x != nil {
		return x.Hw
	}
	return 0
}

func (x *Peer) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatI int32  `protobuf:"fixed32,1,opt,name=lat_i,json=latI,proto3" json:"lat_i,omitempty"`
	LonI int32  `protobuf:"fixed32,2,opt,name=lon_i,json=lonI,proto3" json:"lon_i,omitempty"`
	Alt  int32  `protobuf:"varint,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Time uint32 `protobuf:"fixed32,4,opt,name=time,proto3" json:"time,omitempty"`
	Sats uint32 `protobuf:"varint,19,opt,name=sats,proto3" json:"sats,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *Pos) GetLatI() int32 {
	if x != nil {
		return x.LatI
	}
	return 0
}

func (x *Pos) GetLonI() int32 {
	if x != nil {
		return x.LonI
	}
	return 0
}

func (x *Pos) GetAlt() int32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Pos) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Pos) GetSats() uint32 {
	if x != nil {
		return x.Sats
	}
	return 0
}

type NodeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num       uint32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Peer      *Peer   `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Position  *Pos    `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Snr       float32 `protobuf:"fixed32,4,opt,name=snr,proto3" json:"snr,omitempty"`
	LastHeard uint32  `protobuf:"fixed32,5,opt,name=last_heard,json=lastHeard,proto3" json:"last_heard,omitempty"`
}

func (x *NodeEntry) Reset() {
	*x = NodeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEntry) ProtoMessage() {}

func (x *NodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEntry.ProtoReflect.Descriptor instead.
func (*NodeEntry) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *NodeEntry) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NodeEntry) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *NodeEntry) GetPosition() *Pos {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NodeEntry) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *NodeEntry) GetLastHeard() uint32 {
	if x != nil {
		return x.LastHeard
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level   uint32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type TxQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res    int32  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Free   uint32 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Maxlen uint32 `protobuf:"varint,3,opt,name=maxlen,proto3" json:"maxlen,omitempty"`
}

func (x *TxQueue) Reset() {
	*x = TxQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxQueue) ProtoMessage() {}

func (x *TxQueue) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxQueue.ProtoReflect.Descriptor instead.
func (*TxQueue) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *TxQueue) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *TxQueue) GetFree() uint32 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *TxQueue) GetMaxlen() uint32 {
	if x != nil {
		return x.Maxlen
	}
	return 0
}

type Chan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Settings []byte `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	Role     uint32 `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Chan) Reset() {
	*x = Chan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chan) ProtoMessage() {}

func (x *Chan) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chan.ProtoReflect.Descriptor instead.
func (*Chan) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *Chan) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chan) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Chan) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type RadioConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Section:
	//
	//	*RadioConfig_Device
	//	*RadioConfig_Position
	//	*RadioConfig_Power
	//	*RadioConfig_Network
	//	*RadioConfig_Display
	//	*RadioConfig_Lora
	//	*RadioConfig_Bluetooth
	//	*RadioConfig_Security
	Section isRadioConfig_Section `protobuf_oneof:"section"`
}

func (x *RadioConfig) Reset() {
	*x = RadioConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RadioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioConfig) ProtoMessage() {}

func (x *RadioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioConfig.ProtoReflect.Descriptor instead.
func (*RadioConfig) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{11}
}

func (m *RadioConfig) GetSection() isRadioConfig_Section {
	if m != nil {
		return m.Section
	}
	return nil
}

func (x *RadioConfig) GetDevice() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Device); ok {
		return x.Device
	}
	return nil
}

func (x *RadioConfig) GetPosition() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Position); ok {
		return x.Position
	}
	return nil
}

func (x *RadioConfig) GetPower() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Power); ok {
		return x.Power
	}
	return nil
}

func (x *RadioConfig) GetNetwork() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Network); ok {
		return x.Network
	}
	return nil
}

func (x *RadioConfig) GetDisplay() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Display); ok {
		return x.Display
	}
	return nil
}

func (x *RadioConfig) GetLora() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Lora); ok {
		return x.Lora
	}
	return nil
}

func (x *RadioConfig) GetBluetooth() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Bluetooth); ok {
		return x.Bluetooth
	}
	return nil
}

func (x *RadioConfig) GetSecurity() []byte {
	if x, ok := x.GetSection().(*RadioConfig_Security); ok {
		return x.Security
	}
	return nil
}

type isRadioConfig_Section interface {
	isRadioConfig_Section()
}

type RadioConfig_Device struct {
	Device []byte `protobuf:"bytes,1,opt,name=device,proto3,oneof"`
}

type RadioConfig_Position struct {
	Position []byte `protobuf:"bytes,2,opt,name=position,proto3,oneof"`
}

type RadioConfig_Power struct {
	Power []byte `protobuf:"bytes,3,opt,name=power,proto3,oneof"`
}

type RadioConfig_Network struct {
	Network []byte `protobuf:"bytes,4,opt,name=network,proto3,oneof"`
}

type RadioConfig_Display struct {
	Display []byte `protobuf:"bytes,5,opt,name=display,proto3,oneof"`
}

type RadioConfig_Lora struct {
	Lora []byte `protobuf:"bytes,6,opt,name=lora,proto3,oneof"`
}

type RadioConfig_Bluetooth struct {
	Bluetooth []byte `protobuf:"bytes,7,opt,name=bluetooth,proto3,oneof"`
}

type RadioConfig_Security struct {
	Security []byte `protobuf:"bytes,8,opt,name=security,proto3,oneof"`
}

func (*RadioConfig_Device) isRadioConfig_Section() {}

func (*RadioConfig_Position) isRadioConfig_Section() {}

func (*RadioConfig_Power) isRadioConfig_Section() {}

func (*RadioConfig_Network) isRadioConfig_Section() {}

func (*RadioConfig_Display) isRadioConfig_Section() {}

func (*RadioConfig_Lora) isRadioConfig_Section() {}

func (*RadioConfig_Bluetooth) isRadioConfig_Section() {}

func (*RadioConfig_Security) isRadioConfig_Section() {}

type ModConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Section:
	//
	//	*ModConfig_Mqtt
	//	*ModConfig_Serial
	//	*ModConfig_ExtNotify
	//	*ModConfig_StoreFwd
	//	*ModConfig_RangeTest
	//	*ModConfig_Telemetry
	//	*ModConfig_CannedMsg
	//	*ModConfig_Audio
	//	*ModConfig_RemoteHw
	//	*ModConfig_NeighborInfo
	//	*ModConfig_AmbientLight
	//	*ModConfig_DetectSensor
	//	*ModConfig_Paxcounter
	Section isModConfig_Section `protobuf_oneof:"section"`
}

func (x *ModConfig) Reset() {
	*x = ModConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModConfig) ProtoMessage() {}

func (x *ModConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModConfig.ProtoReflect.Descriptor instead.
func (*ModConfig) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{12}
}

func (m *ModConfig) GetSection() isModConfig_Section {
	if m != nil {
		return m.Section
	}
	return nil
}

func (x *ModConfig) GetMqtt() []byte {
	if x, ok := x.GetSection().(*ModConfig_Mqtt); ok {
		return x.Mqtt
	}
	return nil
}

func (x *ModConfig) GetSerial() []byte {
	if x, ok := x.GetSection().(*ModConfig_Serial); ok {
		return x.Serial
	}
	return nil
}

func (x *ModConfig) GetExtNotify() []byte {
	if x, ok := x.GetSection().(*ModConfig_ExtNotify); ok {
		return x.ExtNotify
	}
	return nil
}

func (x *ModConfig) GetStoreFwd() []byte {
	if x, ok := x.GetSection().(*ModConfig_StoreFwd); ok {
		return x.StoreFwd
	}
	return nil
}

func (x *ModConfig) GetRangeTest() []byte {
	if x, ok := x.GetSection().(*ModConfig_RangeTest); ok {
		return x.RangeTest
	}
	return nil
}

func (x *ModConfig) GetTelemetry() []byte {
	if x, ok := x.GetSection().(*ModConfig_Telemetry); ok {
		return x.Telemetry
	}
	return nil
}

func (x *ModConfig) GetCannedMsg() []byte {
	if x, ok := x.GetSection().(*ModConfig_CannedMsg); ok {
		return x.CannedMsg
	}
	return nil
}

func (x *ModConfig) GetAudio() []byte {
	if x, ok := x.GetSection().(*ModConfig_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *ModConfig) GetRemoteHw() []byte {
	if x, ok := x.GetSection().(*ModConfig_RemoteHw); ok {
		return x.RemoteHw
	}
	return nil
}

func (x *ModConfig) GetNeighborInfo() []byte {
	if x, ok := x.GetSection().(*ModConfig_NeighborInfo); ok {
		return x.NeighborInfo
	}
	return nil
}

func (x *ModConfig) GetAmbientLight() []byte {
	if x, ok := x.GetSection().(*ModConfig_AmbientLight); ok {
		return x.AmbientLight
	}
	return nil
}

func (x *ModConfig) GetDetectSensor() []byte {
	if x, ok := x.GetSection().(*ModConfig_DetectSensor); ok {
		return x.DetectSensor
	}
	return nil
}

func (x *ModConfig) GetPaxcounter() []byte {
	if x, ok := x.GetSection().(*ModConfig_Paxcounter); ok {
		return x.Paxcounter
	}
	return nil
}

type isModConfig_Section interface {
	isModConfig_Section()
}

type ModConfig_Mqtt struct {
	Mqtt []byte `protobuf:"bytes,1,opt,name=mqtt,proto3,oneof"`
}

type ModConfig_Serial struct {
	Serial []byte `protobuf:"bytes,2,opt,name=serial,proto3,oneof"`
}

type ModConfig_ExtNotify struct {
	ExtNotify []byte `protobuf:"bytes,3,opt,name=ext_notify,json=extNotify,proto3,oneof"`
}

type ModConfig_StoreFwd struct {
	StoreFwd []byte `protobuf:"bytes,4,opt,name=store_fwd,json=storeFwd,proto3,oneof"`
}

type ModConfig_RangeTest struct {
	RangeTest []byte `protobuf:"bytes,5,opt,name=range_test,json=rangeTest,proto3,oneof"`
}

type ModConfig_Telemetry struct {
	Telemetry []byte `protobuf:"bytes,6,opt,name=telemetry,proto3,oneof"`
}

type ModConfig_CannedMsg struct {
	CannedMsg []byte `protobuf:"bytes,7,opt,name=canned_msg,json=cannedMsg,proto3,oneof"`
}

type ModConfig_Audio struct {
	Audio []byte `protobuf:"bytes,8,opt,name=audio,proto3,oneof"`
}

type ModConfig_RemoteHw struct {
	RemoteHw []byte `protobuf:"bytes,9,opt,name=remote_hw,json=remoteHw,proto3,oneof"`
}

type ModConfig_NeighborInfo struct {
	NeighborInfo []byte `protobuf:"bytes,10,opt,name=neighbor_info,json=neighborInfo,proto3,oneof"`
}

type ModConfig_AmbientLight struct {
	AmbientLight []byte `protobuf:"bytes,11,opt,name=ambient_light,json=ambientLight,proto3,oneof"`
}

type ModConfig_DetectSensor struct {
	DetectSensor []byte `protobuf:"bytes,12,opt,name=detect_sensor,json=detectSensor,proto3,oneof"`
}

type ModConfig_Paxcounter struct {
	Paxcounter []byte `protobuf:"bytes,13,opt,name=paxcounter,proto3,oneof"`
}

func (*ModConfig_Mqtt) isModConfig_Section() {}

func (*ModConfig_Serial) isModConfig_Section() {}

func (*ModConfig_ExtNotify) isModConfig_Section() {}

func (*ModConfig_StoreFwd) isModConfig_Section() {}

func (*ModConfig_RangeTest) isModConfig_Section() {}

func (*ModConfig_Telemetry) isModConfig_Section() {}

func (*ModConfig_CannedMsg) isModConfig_Section() {}

func (*ModConfig_Audio) isModConfig_Section() {}

func (*ModConfig_RemoteHw) isModConfig_Section() {}

func (*ModConfig_NeighborInfo) isModConfig_Section() {}

func (*ModConfig_AmbientLight) isModConfig_Section() {}

func (*ModConfig_DetectSensor) isModConfig_Section() {}

func (*ModConfig_Paxcounter) isModConfig_Section() {}

type TAKContact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callsign       string `protobuf:"bytes,1,opt,name=callsign,proto3" json:"callsign,omitempty"`
	DeviceCallsign string `protobuf:"bytes,2,opt,name=device_callsign,json=deviceCallsign,proto3" json:"device_callsign,omitempty"`
}

func (x *TAKContact) Reset() {
	*x = TAKContact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKContact) ProtoMessage() {}

func (x *TAKContact) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKContact.ProtoReflect.Descriptor instead.
func (*TAKContact) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *TAKContact) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *TAKContact) GetDeviceCallsign() string {
	if x != nil {
		return x.DeviceCallsign
	}
	return ""
}

type TAKGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role uint32 `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	Team uint32 `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`
}

func (x *TAKGroup) Reset() {
	*x = TAKGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKGroup) ProtoMessage() {}

func (x *TAKGroup) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKGroup.ProtoReflect.Descriptor instead.
func (*TAKGroup) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *TAKGroup) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *TAKGroup) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

type TAKStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Battery uint32 `protobuf:"varint,1,opt,name=battery,proto3" json:"battery,omitempty"`
}

func (x *TAKStatus) Reset() {
	*x = TAKStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKStatus) ProtoMessage() {}

func (x *TAKStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKStatus.ProtoReflect.Descriptor instead.
func (*TAKStatus) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *TAKStatus) GetBattery() uint32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

type TAKPLI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatI   int32  `protobuf:"fixed32,1,opt,name=lat_i,json=latI,proto3" json:"lat_i,omitempty"`
	LonI   int32  `protobuf:"fixed32,2,opt,name=lon_i,json=lonI,proto3" json:"lon_i,omitempty"`
	Alt    int32  `protobuf:"varint,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed  uint32 `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Course uint32 `protobuf:"varint,5,opt,name=course,proto3" json:"course,omitempty"`
}

func (x *TAKPLI) Reset() {
	*x = TAKPLI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKPLI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKPLI) ProtoMessage() {}

func (x *TAKPLI) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKPLI.ProtoReflect.Descriptor instead.
func (*TAKPLI) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *TAKPLI) GetLatI() int32 {
	if x != nil {
		return x.LatI
	}
	return 0
}

func (x *TAKPLI) GetLonI() int32 {
	if x != nil {
		return x.LonI
	}
	return 0
}

func (x *TAKPLI) GetAlt() int32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *TAKPLI) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TAKPLI) GetCourse() uint32 {
	if x != nil {
		return x.Course
	}
	return 0
}

type TAKChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	To      string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *TAKChat) Reset() {
	*x = TAKChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKChat) ProtoMessage() {}

func (x *TAKChat) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKChat.ProtoReflect.Descriptor instead.
func (*TAKChat) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{17}
}

func (x *TAKChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TAKChat) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type TAKPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Compressed bool        `protobuf:"varint,1,opt,name=compressed,proto3" json:"compressed,omitempty"`
	Contact    *TAKContact `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Group      *TAKGroup   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Status     *TAKStatus  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are assignable to Body:
	//
	//	*TAKPacket_Pli
	//	*TAKPacket_Chat
	Body isTAKPacket_Body `protobuf_oneof:"body"`
}

func (x *TAKPacket) Reset() {
	*x = TAKPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAKPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAKPacket) ProtoMessage() {}

func (x *TAKPacket) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAKPacket.ProtoReflect.Descriptor instead.
func (*TAKPacket) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{18}
}

func (x *TAKPacket) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *TAKPacket) GetContact() *TAKContact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *TAKPacket) GetGroup() *TAKGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *TAKPacket) GetStatus() *TAKStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (m *TAKPacket) GetBody() isTAKPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *TAKPacket) GetPli() *TAKPLI {
	if x, ok := x.GetBody().(*TAKPacket_Pli); ok {
		return x.Pli
	}
	return nil
}

func (x *TAKPacket) GetChat() *TAKChat {
	if x, ok := x.GetBody().(*TAKPacket_Chat); ok {
		return x.Chat
	}
	return nil
}

type isTAKPacket_Body interface {
	isTAKPacket_Body()
}

type TAKPacket_Pli struct {
	Pli *TAKPLI `protobuf:"bytes,5,opt,name=pli,proto3,oneof"`
}

type TAKPacket_Chat struct {
	Chat *TAKChat `protobuf:"bytes,6,opt,name=chat,proto3,oneof"`
}

func (*TAKPacket_Pli) isTAKPacket_Body() {}

func (*TAKPacket_Chat) isTAKPacket_Body() {}

type DevMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatteryLevel uint32  `protobuf:"varint,1,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	Voltage      float32 `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	ChUtil       float32 `protobuf:"fixed32,3,opt,name=ch_util,json=chUtil,proto3" json:"ch_util,omitempty"`
	AirUtilTx    float32 `protobuf:"fixed32,4,opt,name=air_util_tx,json=airUtilTx,proto3" json:"air_util_tx,omitempty"`
	Uptime       uint32  `protobuf:"varint,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
}

func (x *DevMetrics) Reset() {
	*x = DevMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevMetrics) ProtoMessage() {}

func (x *DevMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevMetrics.ProtoReflect.Descriptor instead.
func (*DevMetrics) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{19}
}

func (x *DevMetrics) GetBatteryLevel() uint32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *DevMetrics) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *DevMetrics) GetChUtil() float32 {
	if x != nil {
		return x.ChUtil
	}
	return 0
}

func (x *DevMetrics) GetAirUtilTx() float32 {
	if x != nil {
		return x.AirUtilTx
	}
	return 0
}

func (x *DevMetrics) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Telem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time uint32 `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are assignable to Reading:
	//
	//	*Telem_Device
	Reading isTelem_Reading `protobuf_oneof:"reading"`
}

func (x *Telem) Reset() {
	*x = Telem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Telem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telem) ProtoMessage() {}

func (x *Telem) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telem.ProtoReflect.Descriptor instead.
func (*Telem) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{20}
}

func (x *Telem) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (m *Telem) GetReading() isTelem_Reading {
	if m != nil {
		return m.Reading
	}
	return nil
}

func (x *Telem) GetDevice() *DevMetrics {
	if x, ok := x.GetReading().(*Telem_Device); ok {
		return x.Device
	}
	return nil
}

type isTelem_Reading interface {
	isTelem_Reading()
}

type Telem_Device struct {
	Device *DevMetrics `protobuf:"bytes,2,opt,name=device,proto3,oneof"`
}

func (*Telem_Device) isTelem_Reading() {}

var File_mesh_proto protoreflect.FileDescriptor

var file_mesh_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x65,
	0x73, 0x68, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x20, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xbf, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x03, 0x64, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x63, 0x68, 0x12, 0x2b, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x12, 0x1e, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x06, 0x72, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x78,
	0x5f, 0x73, 0x6e, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x78, 0x53, 0x6e,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x70, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x77, 0x61, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x78, 0x5f,
	0x72, 0x73, 0x73, 0x69, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x78, 0x52, 0x73,
	0x73, 0x69, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42,
	0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x62, 0x0a, 0x07, 0x54, 0x6f, 0x52, 0x61, 0x64,
	0x69, 0x6f, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x48, 0x00, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x77, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0c, 0x77, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xa4, 0x03, 0x0a, 0x09,
	0x46, 0x72, 0x6f, 0x6d, 0x52, 0x61, 0x64, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x70, 0x62, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x6c, 0x66, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x12, 0x27, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x52, 0x61,
	0x64, 0x69, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x48, 0x00, 0x52,
	0x03, 0x6c, 0x6f, 0x67, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x00, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70,
	0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x09, 0x6d,
	0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x25, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6c, 0x66, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x50, 0x65,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x61, 0x63,
	0x12, 0x0e, 0x0a, 0x02, 0x68, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x68, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x22, 0x69, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x6c,
	0x61, 0x74, 0x5f, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x04, 0x6c, 0x61, 0x74, 0x49,
	0x12, 0x13, 0x0a, 0x05, 0x6c, 0x6f, 0x6e, 0x5f, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0f, 0x52,
	0x04, 0x6c, 0x6f, 0x6e, 0x49, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x61, 0x74, 0x73, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x61, 0x74, 0x73, 0x22,
	0x99, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x20, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65,
	0x72, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6e,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x73, 0x6e, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x64, 0x22, 0x35, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x22, 0x47, 0x0a, 0x07, 0x54, 0x78, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66,
	0x72, 0x65, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x22, 0x4c, 0x0a, 0x04, 0x43,
	0x68, 0x61, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x0b, 0x52, 0x61,
	0x64, 0x69, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x06, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x12, 0x14, 0x0a, 0x04, 0x6c, 0x6f, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x04, 0x6c, 0x6f, 0x72, 0x61, 0x12, 0x1e, 0x0a, 0x09, 0x62, 0x6c, 0x75, 0x65, 0x74,
	0x6f, 0x6f, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6c,
	0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xb6, 0x03, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14,
	0x0a, 0x04, 0x6d, 0x71, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04,
	0x6d, 0x71, 0x74, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1f,
	0x0a, 0x0a, 0x65, 0x78, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x1d, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x66, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x77, 0x64, 0x12, 0x1f,
	0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12,
	0x1f, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x4d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x5f, 0x68, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x48, 0x77, 0x12, 0x25, 0x0a, 0x0d, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25,
	0x0a, 0x0d, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x6d, 0x62, 0x69, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x25, 0x0a, 0x0d, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x5f,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c,
	0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0a,
	0x70, 0x61, 0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x61, 0x78, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x09,
	0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x0a, 0x54, 0x41, 0x4b,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x73,
	0x69, 0x67, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61,
	0x6c, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x32, 0x0a, 0x08,
	0x54, 0x41, 0x4b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d,
	0x22, 0x25, 0x0a, 0x09, 0x54, 0x41, 0x4b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x22, 0x72, 0x0a, 0x06, 0x54, 0x41, 0x4b, 0x50, 0x4c,
	0x49, 0x12, 0x13, 0x0a, 0x05, 0x6c, 0x61, 0x74, 0x5f, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0f,
	0x52, 0x04, 0x6c, 0x61, 0x74, 0x49, 0x12, 0x13, 0x0a, 0x05, 0x6c, 0x6f, 0x6e, 0x5f, 0x69, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x49, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x54,
	0x41, 0x4b, 0x43, 0x68, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x22, 0xff, 0x01, 0x0a, 0x09, 0x54, 0x41, 0x4b, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x2c,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x41, 0x4b, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x41, 0x4b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x41,
	0x4b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x22, 0x0a, 0x03, 0x70, 0x6c, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x41, 0x4b, 0x50, 0x4c, 0x49, 0x48, 0x00, 0x52, 0x03,
	0x70, 0x6c, 0x69, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x54, 0x41, 0x4b, 0x43, 0x68,
	0x61, 0x74, 0x48, 0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x63, 0x68, 0x55, 0x74, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x69, 0x72,
	0x5f, 0x75, 0x74, 0x69, 0x6c, 0x5f, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x61, 0x69, 0x72, 0x55, 0x74, 0x69, 0x6c, 0x54, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x54, 0x0a, 0x05, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x2a, 0x99, 0x01, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x44,
	0x45, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4f, 0x52, 0x54, 0x5f,
	0x54, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x54, 0x52, 0x59, 0x10, 0x43, 0x12, 0x0c, 0x0a, 0x08, 0x50,
	0x4f, 0x52, 0x54, 0x5f, 0x54, 0x41, 0x4b, 0x10, 0x48, 0x12, 0x17, 0x0a, 0x12, 0x50, 0x4f, 0x52,
	0x54, 0x5f, 0x54, 0x41, 0x4b, 0x5f, 0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44, 0x45, 0x52, 0x10,
	0x81, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x48, 0x59, 0x44, 0x52, 0x49,
	0x53, 0x10, 0x4e, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x71, 0x61, 0x69, 0x2f, 0x68, 0x79, 0x64,
	0x72, 0x69, 0x73, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x68,
	0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData = file_mesh_proto_rawDesc
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(file_mesh_proto_rawDescData)
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_mesh_proto_goTypes = []interface{}{
	(Port)(0),           // 0: meshpb.Port
	(*Payload)(nil),     // 1: meshpb.Payload
	(*Packet)(nil),      // 2: meshpb.Packet
	(*ToRadio)(nil),     // 3: meshpb.ToRadio
	(*FromRadio)(nil),   // 4: meshpb.FromRadio
	(*NodeSelf)(nil),    // 5: meshpb.NodeSelf
	(*Peer)(nil),        // 6: meshpb.Peer
	(*Pos)(nil),         // 7: meshpb.Pos
	(*NodeEntry)(nil),   // 8: meshpb.NodeEntry
	(*Log)(nil),         // 9: meshpb.Log
	(*TxQueue)(nil),     // 10: meshpb.TxQueue
	(*Chan)(nil),        // 11: meshpb.Chan
	(*RadioConfig)(nil), // 12: meshpb.RadioConfig
	(*ModConfig)(nil),   // 13: meshpb.ModConfig
	(*TAKContact)(nil),  // 14: meshpb.TAKContact
	(*TAKGroup)(nil),    // 15: meshpb.TAKGroup
	(*TAKStatus)(nil),   // 16: meshpb.TAKStatus
	(*TAKPLI)(nil),      // 17: meshpb.TAKPLI
	(*TAKChat)(nil),     // 18: meshpb.TAKChat
	(*TAKPacket)(nil),   // 19: meshpb.TAKPacket
	(*DevMetrics)(nil),  // 20: meshpb.DevMetrics
	(*Telem)(nil),       // 21: meshpb.Telem
}
var file_mesh_proto_depIdxs = []int32{
	0,  // 0: meshpb.Payload.port:type_name -> meshpb.Port
	1,  // 1: meshpb.Packet.decoded:type_name -> meshpb.Payload
	2,  // 2: meshpb.ToRadio.packet:type_name -> meshpb.Packet
	2,  // 3: meshpb.FromRadio.packet:type_name -> meshpb.Packet
	5,  // 4: meshpb.FromRadio.self:type_name -> meshpb.NodeSelf
	8,  // 5: meshpb.FromRadio.node:type_name -> meshpb.NodeEntry
	12, // 6: meshpb.FromRadio.config:type_name -> meshpb.RadioConfig
	9,  // 7: meshpb.FromRadio.log:type_name -> meshpb.Log
	13, // 8: meshpb.FromRadio.mod_config:type_name -> meshpb.ModConfig
	11, // 9: meshpb.FromRadio.channel:type_name -> meshpb.Chan
	10, // 10: meshpb.FromRadio.queue:type_name -> meshpb.TxQueue
	6,  // 11: meshpb.NodeEntry.peer:type_name -> meshpb.Peer
	7,  // 12: meshpb.NodeEntry.position:type_name -> meshpb.Pos
	14, // 13: meshpb.TAKPacket.contact:type_name -> meshpb.TAKContact
	15, // 14: meshpb.TAKPacket.group:type_name -> meshpb.TAKGroup
	16, // 15: meshpb.TAKPacket.status:type_name -> meshpb.TAKStatus
	17, // 16: meshpb.TAKPacket.pli:type_name -> meshpb.TAKPLI
	18, // 17: meshpb.TAKPacket.chat:type_name -> meshpb.TAKChat
	20, // 18: meshpb.Telem.device:type_name -> meshpb.DevMetrics
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mesh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToRadio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromRadio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSelf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RadioConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKContact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKPLI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAKPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Telem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mesh_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Packet_Decoded)(nil),
		(*Packet_Encrypted)(nil),
	}
	file_mesh_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ToRadio_Packet)(nil),
		(*ToRadio_WantConfigId)(nil),
	}
	file_mesh_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*FromRadio_Packet)(nil),
		(*FromRadio_Self)(nil),
		(*FromRadio_Node)(nil),
		(*FromRadio_Config)(nil),
		(*FromRadio_Log)(nil),
		(*FromRadio_ConfigCompleteId)(nil),
		(*FromRadio_ModConfig)(nil),
		(*FromRadio_Channel)(nil),
		(*FromRadio_Queue)(nil),
	}
	file_mesh_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*RadioConfig_Device)(nil),
		(*RadioConfig_Position)(nil),
		(*RadioConfig_Power)(nil),
		(*RadioConfig_Network)(nil),
		(*RadioConfig_Display)(nil),
		(*RadioConfig_Lora)(nil),
		(*RadioConfig_Bluetooth)(nil),
		(*RadioConfig_Security)(nil),
	}
	file_mesh_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ModConfig_Mqtt)(nil),
		(*ModConfig_Serial)(nil),
		(*ModConfig_ExtNotify)(nil),
		(*ModConfig_StoreFwd)(nil),
		(*ModConfig_RangeTest)(nil),
		(*ModConfig_Telemetry)(nil),
		(*ModConfig_CannedMsg)(nil),
		(*ModConfig_Audio)(nil),
		(*ModConfig_RemoteHw)(nil),
		(*ModConfig_NeighborInfo)(nil),
		(*ModConfig_AmbientLight)(nil),
		(*ModConfig_DetectSensor)(nil),
		(*ModConfig_Paxcounter)(nil),
	}
	file_mesh_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*TAKPacket_Pli)(nil),
		(*TAKPacket_Chat)(nil),
	}
	file_mesh_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*Telem_Device)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mesh_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_rawDesc = nil
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
