package transform

import (
	"testing"

	"github.com/projectqai/hydris/engine/meta"
	pb "github.com/projectqai/proto/go"
)

// TestTransformersPreserveNonGeneratedFields ensures that running all
// transformers on an entity does not overwrite fields that are not
// produced by that transformer.
func TestTransformersPreserveNonGeneratedFields(t *testing.T) {
	rangeMax := 1000.0
	fov := 90.0
	alt := 100.0

	head := map[string]*pb.Entity{
		"parent": {
			Id: "parent",
			Geo: &pb.GeoSpatialComponent{
				Latitude:  48.0,
				Longitude: 11.0,
				Altitude:  &alt,
			},
			Orientation: &pb.OrientationComponent{
				Orientation: &pb.Quaternion{W: 1, X: 0, Y: 0, Z: 0},
			},
		},
		"sensor": {
			Id:    "sensor",
			Label: strPtr("my sensor"),
			Pose: &pb.PoseComponent{
				Parent: "parent",
				Offset: &pb.PoseComponent_Cartesian{
					Cartesian: &pb.CartesianOffset{EastM: 10, NorthM: 20},
				},
			},
			Symbol: &pb.SymbolComponent{MilStd2525C: "SFGPUCI--------"},
			Camera: &pb.CameraComponent{
				RangeMax: &rangeMax,
				Fov:      &fov,
			},
			Track:          &pb.TrackComponent{Tracker: strPtr("tracker-1")},
			Administrative: &pb.AdministrativeComponent{Flag: strPtr("DE")},
			Transponder:    &pb.TransponderComponent{Ais: &pb.TransponderAIS{}},
			LocalShape: &pb.LocalShapeComponent{
				RelativeTo: "parent",
				Geometry: &pb.LocalGeometry{
					Shape: &pb.LocalGeometry_Circle{
						Circle: &pb.LocalCircle{
							Center:  &pb.LocalPoint{EastM: 0, NorthM: 0},
							RadiusM: 500,
						},
					},
				},
			},
		},
	}

	transformers := []Transformer{
		NewPolarNormalizeTransformer(),
		NewPoseTransformer(),
		NewShapeTransformer(),
		NewClassificationTransformer(),
		NewAOUTransformer(),
		NewCameraTransformer(),
		NewMediaTransformer(),
		NewChatTransformer(),
	}

	components := map[int32]meta.Component{
		12: {Generated: false}, // symbol is user-authored
	}

	bus := &noopBus{}
	RunTransformers(transformers, head, bus, "sensor", components)

	e := head["sensor"]
	if e == nil {
		t.Fatal("entity disappeared from head")
	}

	if e.Label == nil || *e.Label != "my sensor" {
		t.Error("Label was overwritten")
	}
	if e.Track == nil || e.Track.Tracker == nil || *e.Track.Tracker != "tracker-1" {
		t.Error("TrackComponent was overwritten")
	}
	if e.Administrative == nil || e.Administrative.Flag == nil || *e.Administrative.Flag != "DE" {
		t.Error("AdministrativeComponent was overwritten")
	}
	if e.Transponder == nil || e.Transponder.Ais == nil {
		t.Error("TransponderComponent was overwritten")
	}
	if e.Pose == nil || e.Pose.Parent != "parent" {
		t.Error("PoseComponent was overwritten")
	}
	if e.Symbol == nil || e.Symbol.MilStd2525C != "SFGPUCI--------" {
		t.Errorf("SymbolComponent was overwritten: got %v", e.Symbol)
	}
	if e.LocalShape == nil || e.LocalShape.RelativeTo != "parent" {
		t.Error("LocalShapeComponent was overwritten")
	}
	if e.LocalShape != nil && e.LocalShape.Geometry != nil {
		if c, ok := e.LocalShape.Geometry.Shape.(*pb.LocalGeometry_Circle); ok {
			if c.Circle.RadiusM != 500 {
				t.Errorf("LocalShape circle radius was overwritten: got %v", c.Circle.RadiusM)
			}
		}
	}
}

// TestTransformersPreserveUnrelatedFieldsOnPoseChild verifies that the pose
// transformer resolving geo/orientation does not touch other fields.
func TestTransformersPreserveUnrelatedFieldsOnPoseChild(t *testing.T) {
	alt := 50.0
	head := map[string]*pb.Entity{
		"parent": {
			Id: "parent",
			Geo: &pb.GeoSpatialComponent{
				Latitude:  52.0,
				Longitude: 13.0,
				Altitude:  &alt,
			},
		},
		"child": {
			Id:    "child",
			Label: strPtr("detection-1"),
			Pose: &pb.PoseComponent{
				Parent: "parent",
				Offset: &pb.PoseComponent_Polar{
					Polar: &pb.PolarOffset{
						Azimuth: 45.0,
						Range:   floatPtr(1000),
					},
				},
			},
			Detection:      &pb.DetectionComponent{},
			Track:          &pb.TrackComponent{Tracker: strPtr("trk-7")},
			Administrative: &pb.AdministrativeComponent{Flag: strPtr("US")},
		},
	}

	transformers := []Transformer{
		NewPolarNormalizeTransformer(),
		NewPoseTransformer(),
		NewShapeTransformer(),
		NewClassificationTransformer(),
		NewAOUTransformer(),
		NewCameraTransformer(),
		NewMediaTransformer(),
		NewChatTransformer(),
	}

	bus := &noopBus{}
	RunTransformers(transformers, head, bus, "child", nil)

	e := head["child"]
	if e == nil {
		t.Fatal("entity disappeared from head")
	}

	if e.Geo == nil {
		t.Error("expected Geo to be generated by PoseTransformer")
	}

	if e.Label == nil || *e.Label != "detection-1" {
		t.Error("Label was overwritten")
	}
	if e.Track == nil || e.Track.Tracker == nil || *e.Track.Tracker != "trk-7" {
		t.Error("TrackComponent was overwritten")
	}
	if e.Administrative == nil || e.Administrative.Flag == nil || *e.Administrative.Flag != "US" {
		t.Error("AdministrativeComponent was overwritten")
	}
	if e.Detection == nil {
		t.Error("DetectionComponent was overwritten")
	}
	if e.Pose == nil || e.Pose.Parent != "parent" {
		t.Error("PoseComponent was overwritten")
	}
}

type noopBus struct{}

func (n *noopBus) Dirty(string, *pb.Entity, pb.EntityChange) {}

func strPtr(s string) *string     { return &s }
func floatPtr(f float64) *float64 { return &f }
