// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file timeline.proto (package timeline, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message timeline.GetTimelineRequest
 */
export class GetTimelineRequest extends Message<GetTimelineRequest> {
  constructor(data?: PartialMessage<GetTimelineRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "timeline.GetTimelineRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTimelineRequest {
    return new GetTimelineRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTimelineRequest {
    return new GetTimelineRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTimelineRequest {
    return new GetTimelineRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTimelineRequest | PlainMessage<GetTimelineRequest> | undefined, b: GetTimelineRequest | PlainMessage<GetTimelineRequest> | undefined): boolean {
    return proto3.util.equals(GetTimelineRequest, a, b);
  }
}

/**
 * @generated from message timeline.GetTimelineResponse
 */
export class GetTimelineResponse extends Message<GetTimelineResponse> {
  /**
   * @generated from field: google.protobuf.Timestamp min = 1;
   */
  min?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp max = 2;
   */
  max?: Timestamp;

  /**
   * @generated from field: bool frozen = 3;
   */
  frozen = false;

  /**
   * @generated from field: google.protobuf.Timestamp at = 4;
   */
  at?: Timestamp;

  constructor(data?: PartialMessage<GetTimelineResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "timeline.GetTimelineResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "min", kind: "message", T: Timestamp },
    { no: 2, name: "max", kind: "message", T: Timestamp },
    { no: 3, name: "frozen", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTimelineResponse {
    return new GetTimelineResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTimelineResponse {
    return new GetTimelineResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTimelineResponse {
    return new GetTimelineResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTimelineResponse | PlainMessage<GetTimelineResponse> | undefined, b: GetTimelineResponse | PlainMessage<GetTimelineResponse> | undefined): boolean {
    return proto3.util.equals(GetTimelineResponse, a, b);
  }
}

/**
 * @generated from message timeline.MoveTimelineRequest
 */
export class MoveTimelineRequest extends Message<MoveTimelineRequest> {
  /**
   * @generated from field: bool freeze = 1;
   */
  freeze = false;

  /**
   * @generated from field: google.protobuf.Timestamp at = 2;
   */
  at?: Timestamp;

  constructor(data?: PartialMessage<MoveTimelineRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "timeline.MoveTimelineRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "freeze", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveTimelineRequest {
    return new MoveTimelineRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveTimelineRequest {
    return new MoveTimelineRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveTimelineRequest {
    return new MoveTimelineRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MoveTimelineRequest | PlainMessage<MoveTimelineRequest> | undefined, b: MoveTimelineRequest | PlainMessage<MoveTimelineRequest> | undefined): boolean {
    return proto3.util.equals(MoveTimelineRequest, a, b);
  }
}

/**
 * @generated from message timeline.MoveTimelineResponse
 */
export class MoveTimelineResponse extends Message<MoveTimelineResponse> {
  /**
   * @generated from field: google.protobuf.Timestamp current = 1;
   */
  current?: Timestamp;

  constructor(data?: PartialMessage<MoveTimelineResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "timeline.MoveTimelineResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "current", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveTimelineResponse {
    return new MoveTimelineResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveTimelineResponse {
    return new MoveTimelineResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveTimelineResponse {
    return new MoveTimelineResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MoveTimelineResponse | PlainMessage<MoveTimelineResponse> | undefined, b: MoveTimelineResponse | PlainMessage<MoveTimelineResponse> | undefined): boolean {
    return proto3.util.equals(MoveTimelineResponse, a, b);
  }
}

