// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file timeline.proto (package timeline, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTimelineRequest, GetTimelineResponse, MoveTimelineRequest, MoveTimelineResponse } from "./timeline_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service timeline.TimelineService
 */
export const TimelineService = {
  typeName: "timeline.TimelineService",
  methods: {
    /**
     * @generated from rpc timeline.TimelineService.MoveTimeline
     */
    moveTimeline: {
      name: "MoveTimeline",
      I: MoveTimelineRequest,
      O: MoveTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc timeline.TimelineService.GetTimeline
     */
    getTimeline: {
      name: "GetTimeline",
      I: GetTimelineRequest,
      O: GetTimelineResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

