// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file world.proto (package world, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum world.EntityChange
 */
export enum EntityChange {
  /**
   * @generated from enum value: Invalid = 0;
   */
  Invalid = 0,

  /**
   * @generated from enum value: Updated = 1;
   */
  Updated = 1,

  /**
   * @generated from enum value: Expired = 2;
   */
  Expired = 2,

  /**
   * @generated from enum value: Unobserved = 3;
   */
  Unobserved = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(EntityChange)
proto3.util.setEnumType(EntityChange, "world.EntityChange", [
  { no: 0, name: "Invalid" },
  { no: 1, name: "Updated" },
  { no: 2, name: "Expired" },
  { no: 3, name: "Unobserved" },
]);

/**
 * @generated from message world.Entity
 */
export class Entity extends Message<Entity> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string label = 2;
   */
  label?: string;

  /**
   * @generated from field: optional world.ControllerRef controller = 3;
   */
  controller?: ControllerRef;

  /**
   * @generated from field: optional world.Lifetime lifetime = 4;
   */
  lifetime?: Lifetime;

  /**
   * @generated from field: optional world.GeoSpatialComponent geo = 11;
   */
  geo?: GeoSpatialComponent;

  /**
   * @generated from field: optional world.SymbolComponent symbol = 12;
   */
  symbol?: SymbolComponent;

  /**
   * @generated from field: optional world.CameraComponent camera = 15;
   */
  camera?: CameraComponent;

  /**
   * @generated from field: optional world.DetectionComponent detection = 16;
   */
  detection?: DetectionComponent;

  /**
   * @generated from field: optional world.BearingComponent bearing = 17;
   */
  bearing?: BearingComponent;

  /**
   * @generated from field: optional world.LocationUncertaintyComponent locationUncertainty = 20;
   */
  locationUncertainty?: LocationUncertaintyComponent;

  constructor(data?: PartialMessage<Entity>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.Entity";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "controller", kind: "message", T: ControllerRef, opt: true },
    { no: 4, name: "lifetime", kind: "message", T: Lifetime, opt: true },
    { no: 11, name: "geo", kind: "message", T: GeoSpatialComponent, opt: true },
    { no: 12, name: "symbol", kind: "message", T: SymbolComponent, opt: true },
    { no: 15, name: "camera", kind: "message", T: CameraComponent, opt: true },
    { no: 16, name: "detection", kind: "message", T: DetectionComponent, opt: true },
    { no: 17, name: "bearing", kind: "message", T: BearingComponent, opt: true },
    { no: 20, name: "locationUncertainty", kind: "message", T: LocationUncertaintyComponent, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Entity {
    return new Entity().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Entity {
    return new Entity().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Entity {
    return new Entity().fromJsonString(jsonString, options);
  }

  static equals(a: Entity | PlainMessage<Entity> | undefined, b: Entity | PlainMessage<Entity> | undefined): boolean {
    return proto3.util.equals(Entity, a, b);
  }
}

/**
 * @generated from message world.ControllerRef
 */
export class ControllerRef extends Message<ControllerRef> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<ControllerRef>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.ControllerRef";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ControllerRef {
    return new ControllerRef().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ControllerRef {
    return new ControllerRef().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ControllerRef {
    return new ControllerRef().fromJsonString(jsonString, options);
  }

  static equals(a: ControllerRef | PlainMessage<ControllerRef> | undefined, b: ControllerRef | PlainMessage<ControllerRef> | undefined): boolean {
    return proto3.util.equals(ControllerRef, a, b);
  }
}

/**
 * @generated from message world.Lifetime
 */
export class Lifetime extends Message<Lifetime> {
  /**
   * @generated from field: optional google.protobuf.Timestamp from = 1;
   */
  from?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp until = 2;
   */
  until?: Timestamp;

  constructor(data?: PartialMessage<Lifetime>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.Lifetime";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from", kind: "message", T: Timestamp, opt: true },
    { no: 2, name: "until", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Lifetime {
    return new Lifetime().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Lifetime {
    return new Lifetime().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Lifetime {
    return new Lifetime().fromJsonString(jsonString, options);
  }

  static equals(a: Lifetime | PlainMessage<Lifetime> | undefined, b: Lifetime | PlainMessage<Lifetime> | undefined): boolean {
    return proto3.util.equals(Lifetime, a, b);
  }
}

/**
 * @generated from message world.GeoSpatialComponent
 */
export class GeoSpatialComponent extends Message<GeoSpatialComponent> {
  /**
   * @generated from field: double longitude = 1;
   */
  longitude = 0;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude = 0;

  /**
   * @generated from field: double altitude = 3;
   */
  altitude = 0;

  constructor(data?: PartialMessage<GeoSpatialComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.GeoSpatialComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "altitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoSpatialComponent {
    return new GeoSpatialComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoSpatialComponent {
    return new GeoSpatialComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoSpatialComponent {
    return new GeoSpatialComponent().fromJsonString(jsonString, options);
  }

  static equals(a: GeoSpatialComponent | PlainMessage<GeoSpatialComponent> | undefined, b: GeoSpatialComponent | PlainMessage<GeoSpatialComponent> | undefined): boolean {
    return proto3.util.equals(GeoSpatialComponent, a, b);
  }
}

/**
 * @generated from message world.SymbolComponent
 */
export class SymbolComponent extends Message<SymbolComponent> {
  /**
   * @generated from field: string milStd2525C = 1;
   */
  milStd2525C = "";

  constructor(data?: PartialMessage<SymbolComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.SymbolComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "milStd2525C", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SymbolComponent {
    return new SymbolComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SymbolComponent {
    return new SymbolComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SymbolComponent {
    return new SymbolComponent().fromJsonString(jsonString, options);
  }

  static equals(a: SymbolComponent | PlainMessage<SymbolComponent> | undefined, b: SymbolComponent | PlainMessage<SymbolComponent> | undefined): boolean {
    return proto3.util.equals(SymbolComponent, a, b);
  }
}

/**
 * @generated from message world.Camera
 */
export class Camera extends Message<Camera> {
  /**
   * @generated from field: string label = 1;
   */
  label = "";

  /**
   * @generated from field: string url = 2;
   */
  url = "";

  constructor(data?: PartialMessage<Camera>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.Camera";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Camera {
    return new Camera().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Camera {
    return new Camera().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Camera {
    return new Camera().fromJsonString(jsonString, options);
  }

  static equals(a: Camera | PlainMessage<Camera> | undefined, b: Camera | PlainMessage<Camera> | undefined): boolean {
    return proto3.util.equals(Camera, a, b);
  }
}

/**
 * @generated from message world.CameraComponent
 */
export class CameraComponent extends Message<CameraComponent> {
  /**
   * @generated from field: repeated world.Camera cameras = 1;
   */
  cameras: Camera[] = [];

  constructor(data?: PartialMessage<CameraComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.CameraComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cameras", kind: "message", T: Camera, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CameraComponent {
    return new CameraComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CameraComponent {
    return new CameraComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CameraComponent {
    return new CameraComponent().fromJsonString(jsonString, options);
  }

  static equals(a: CameraComponent | PlainMessage<CameraComponent> | undefined, b: CameraComponent | PlainMessage<CameraComponent> | undefined): boolean {
    return proto3.util.equals(CameraComponent, a, b);
  }
}

/**
 * @generated from message world.DetectionComponent
 */
export class DetectionComponent extends Message<DetectionComponent> {
  /**
   * @generated from field: optional string detectorEntityID = 1;
   */
  detectorEntityID?: string;

  /**
   * @generated from field: optional string classification = 2;
   */
  classification?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp lastMeasured = 3;
   */
  lastMeasured?: Timestamp;

  constructor(data?: PartialMessage<DetectionComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.DetectionComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "detectorEntityID", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "classification", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "lastMeasured", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetectionComponent {
    return new DetectionComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetectionComponent {
    return new DetectionComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetectionComponent {
    return new DetectionComponent().fromJsonString(jsonString, options);
  }

  static equals(a: DetectionComponent | PlainMessage<DetectionComponent> | undefined, b: DetectionComponent | PlainMessage<DetectionComponent> | undefined): boolean {
    return proto3.util.equals(DetectionComponent, a, b);
  }
}

/**
 * @generated from message world.BearingComponent
 */
export class BearingComponent extends Message<BearingComponent> {
  /**
   * @generated from field: optional double azimuth = 1;
   */
  azimuth?: number;

  /**
   * @generated from field: optional double elevation = 2;
   */
  elevation?: number;

  constructor(data?: PartialMessage<BearingComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.BearingComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "azimuth", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 2, name: "elevation", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BearingComponent {
    return new BearingComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BearingComponent {
    return new BearingComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BearingComponent {
    return new BearingComponent().fromJsonString(jsonString, options);
  }

  static equals(a: BearingComponent | PlainMessage<BearingComponent> | undefined, b: BearingComponent | PlainMessage<BearingComponent> | undefined): boolean {
    return proto3.util.equals(BearingComponent, a, b);
  }
}

/**
 * @generated from message world.CovarianceMatrix
 */
export class CovarianceMatrix extends Message<CovarianceMatrix> {
  /**
   * @generated from field: optional double mxx = 1;
   */
  mxx?: number;

  /**
   * @generated from field: optional double mxy = 2;
   */
  mxy?: number;

  /**
   * @generated from field: optional double mxz = 3;
   */
  mxz?: number;

  /**
   * @generated from field: optional double myy = 4;
   */
  myy?: number;

  /**
   * @generated from field: optional double myz = 5;
   */
  myz?: number;

  /**
   * @generated from field: optional double mzz = 6;
   */
  mzz?: number;

  constructor(data?: PartialMessage<CovarianceMatrix>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.CovarianceMatrix";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mxx", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 2, name: "mxy", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 3, name: "mxz", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 4, name: "myy", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "myz", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "mzz", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CovarianceMatrix {
    return new CovarianceMatrix().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CovarianceMatrix {
    return new CovarianceMatrix().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CovarianceMatrix {
    return new CovarianceMatrix().fromJsonString(jsonString, options);
  }

  static equals(a: CovarianceMatrix | PlainMessage<CovarianceMatrix> | undefined, b: CovarianceMatrix | PlainMessage<CovarianceMatrix> | undefined): boolean {
    return proto3.util.equals(CovarianceMatrix, a, b);
  }
}

/**
 * @generated from message world.LocationUncertaintyComponent
 */
export class LocationUncertaintyComponent extends Message<LocationUncertaintyComponent> {
  /**
   * @generated from field: optional world.CovarianceMatrix positionEnuCov = 1;
   */
  positionEnuCov?: CovarianceMatrix;

  /**
   * @generated from field: optional world.CovarianceMatrix velocityEnuCov = 2;
   */
  velocityEnuCov?: CovarianceMatrix;

  constructor(data?: PartialMessage<LocationUncertaintyComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.LocationUncertaintyComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "positionEnuCov", kind: "message", T: CovarianceMatrix, opt: true },
    { no: 2, name: "velocityEnuCov", kind: "message", T: CovarianceMatrix, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocationUncertaintyComponent {
    return new LocationUncertaintyComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocationUncertaintyComponent {
    return new LocationUncertaintyComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocationUncertaintyComponent {
    return new LocationUncertaintyComponent().fromJsonString(jsonString, options);
  }

  static equals(a: LocationUncertaintyComponent | PlainMessage<LocationUncertaintyComponent> | undefined, b: LocationUncertaintyComponent | PlainMessage<LocationUncertaintyComponent> | undefined): boolean {
    return proto3.util.equals(LocationUncertaintyComponent, a, b);
  }
}

/**
 * @generated from message world.Geometry
 */
export class Geometry extends Message<Geometry> {
  /**
   * @generated from field: bytes wkb = 1;
   */
  wkb = new Uint8Array(0);

  constructor(data?: PartialMessage<Geometry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.Geometry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "wkb", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Geometry {
    return new Geometry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Geometry {
    return new Geometry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Geometry {
    return new Geometry().fromJsonString(jsonString, options);
  }

  static equals(a: Geometry | PlainMessage<Geometry> | undefined, b: Geometry | PlainMessage<Geometry> | undefined): boolean {
    return proto3.util.equals(Geometry, a, b);
  }
}

/**
 * @generated from message world.ListEntitiesRequest
 */
export class ListEntitiesRequest extends Message<ListEntitiesRequest> {
  /**
   * @generated from field: optional world.Geometry geo = 2;
   */
  geo?: Geometry;

  constructor(data?: PartialMessage<ListEntitiesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.ListEntitiesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "geo", kind: "message", T: Geometry, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEntitiesRequest {
    return new ListEntitiesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEntitiesRequest {
    return new ListEntitiesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEntitiesRequest {
    return new ListEntitiesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEntitiesRequest | PlainMessage<ListEntitiesRequest> | undefined, b: ListEntitiesRequest | PlainMessage<ListEntitiesRequest> | undefined): boolean {
    return proto3.util.equals(ListEntitiesRequest, a, b);
  }
}

/**
 * @generated from message world.ListEntitiesResponse
 */
export class ListEntitiesResponse extends Message<ListEntitiesResponse> {
  /**
   * @generated from field: repeated world.Entity entities = 1;
   */
  entities: Entity[] = [];

  constructor(data?: PartialMessage<ListEntitiesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.ListEntitiesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entities", kind: "message", T: Entity, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEntitiesResponse {
    return new ListEntitiesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEntitiesResponse {
    return new ListEntitiesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEntitiesResponse {
    return new ListEntitiesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEntitiesResponse | PlainMessage<ListEntitiesResponse> | undefined, b: ListEntitiesResponse | PlainMessage<ListEntitiesResponse> | undefined): boolean {
    return proto3.util.equals(ListEntitiesResponse, a, b);
  }
}

/**
 * @generated from message world.EntityChangeRequest
 */
export class EntityChangeRequest extends Message<EntityChangeRequest> {
  /**
   * @generated from field: repeated world.Entity changes = 1;
   */
  changes: Entity[] = [];

  constructor(data?: PartialMessage<EntityChangeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.EntityChangeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "changes", kind: "message", T: Entity, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EntityChangeRequest {
    return new EntityChangeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EntityChangeRequest {
    return new EntityChangeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EntityChangeRequest {
    return new EntityChangeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EntityChangeRequest | PlainMessage<EntityChangeRequest> | undefined, b: EntityChangeRequest | PlainMessage<EntityChangeRequest> | undefined): boolean {
    return proto3.util.equals(EntityChangeRequest, a, b);
  }
}

/**
 * @generated from message world.EntityChangeResponse
 */
export class EntityChangeResponse extends Message<EntityChangeResponse> {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted = false;

  /**
   * @generated from field: string debug = 2;
   */
  debug = "";

  constructor(data?: PartialMessage<EntityChangeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.EntityChangeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "accepted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "debug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EntityChangeResponse {
    return new EntityChangeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EntityChangeResponse {
    return new EntityChangeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EntityChangeResponse {
    return new EntityChangeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EntityChangeResponse | PlainMessage<EntityChangeResponse> | undefined, b: EntityChangeResponse | PlainMessage<EntityChangeResponse> | undefined): boolean {
    return proto3.util.equals(EntityChangeResponse, a, b);
  }
}

/**
 * @generated from message world.EntityChangeEvent
 */
export class EntityChangeEvent extends Message<EntityChangeEvent> {
  /**
   * @generated from field: world.Entity entity = 1;
   */
  entity?: Entity;

  /**
   * @generated from field: world.EntityChange t = 2;
   */
  t = EntityChange.Invalid;

  constructor(data?: PartialMessage<EntityChangeEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.EntityChangeEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity", kind: "message", T: Entity },
    { no: 2, name: "t", kind: "enum", T: proto3.getEnumType(EntityChange) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EntityChangeEvent {
    return new EntityChangeEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EntityChangeEvent {
    return new EntityChangeEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EntityChangeEvent {
    return new EntityChangeEvent().fromJsonString(jsonString, options);
  }

  static equals(a: EntityChangeEvent | PlainMessage<EntityChangeEvent> | undefined, b: EntityChangeEvent | PlainMessage<EntityChangeEvent> | undefined): boolean {
    return proto3.util.equals(EntityChangeEvent, a, b);
  }
}

/**
 * @generated from message world.GetEntityRequest
 */
export class GetEntityRequest extends Message<GetEntityRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetEntityRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.GetEntityRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEntityRequest {
    return new GetEntityRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEntityRequest {
    return new GetEntityRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEntityRequest {
    return new GetEntityRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEntityRequest | PlainMessage<GetEntityRequest> | undefined, b: GetEntityRequest | PlainMessage<GetEntityRequest> | undefined): boolean {
    return proto3.util.equals(GetEntityRequest, a, b);
  }
}

/**
 * @generated from message world.GetEntityResponse
 */
export class GetEntityResponse extends Message<GetEntityResponse> {
  /**
   * @generated from field: world.Entity entity = 1;
   */
  entity?: Entity;

  constructor(data?: PartialMessage<GetEntityResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.GetEntityResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity", kind: "message", T: Entity },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEntityResponse {
    return new GetEntityResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEntityResponse {
    return new GetEntityResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEntityResponse {
    return new GetEntityResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEntityResponse | PlainMessage<GetEntityResponse> | undefined, b: GetEntityResponse | PlainMessage<GetEntityResponse> | undefined): boolean {
    return proto3.util.equals(GetEntityResponse, a, b);
  }
}

/**
 * @generated from message world.ObserverRequest
 */
export class ObserverRequest extends Message<ObserverRequest> {
  constructor(data?: PartialMessage<ObserverRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.ObserverRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ObserverRequest {
    return new ObserverRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ObserverRequest {
    return new ObserverRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ObserverRequest {
    return new ObserverRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ObserverRequest | PlainMessage<ObserverRequest> | undefined, b: ObserverRequest | PlainMessage<ObserverRequest> | undefined): boolean {
    return proto3.util.equals(ObserverRequest, a, b);
  }
}

/**
 * @generated from message world.ObserverState
 */
export class ObserverState extends Message<ObserverState> {
  /**
   * @generated from field: world.Geometry geo = 1;
   */
  geo?: Geometry;

  /**
   * @generated from field: optional google.protobuf.Timestamp viewHistory = 2;
   */
  viewHistory?: Timestamp;

  constructor(data?: PartialMessage<ObserverState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "world.ObserverState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "geo", kind: "message", T: Geometry },
    { no: 2, name: "viewHistory", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ObserverState {
    return new ObserverState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ObserverState {
    return new ObserverState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ObserverState {
    return new ObserverState().fromJsonString(jsonString, options);
  }

  static equals(a: ObserverState | PlainMessage<ObserverState> | undefined, b: ObserverState | PlainMessage<ObserverState> | undefined): boolean {
    return proto3.util.equals(ObserverState, a, b);
  }
}

